name: Checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, types]

    name: ${{ matrix.task }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - run: npm run ${{ matrix.task }}
