name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  vitest-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - run: npm run test
